Repository Ureka-miniProject/AnalDoo-FE, pull requests merged in 2025-05, with the labels that each got.

#4 [FEAT] 대회 생성 페이지 구현
  package-lock.json
  package.json
  src/api/index.js
  src/components/CreateMatch.vue
  src/components/HeaderBar.vue
  src/router.js
  vue.config.js
Labels: feat

#6 [FIX] 최소 참가 인원 삭제
  src/components/CreateMatch.vue
Labels: fix

#9 [FEAT] 예약 생성 api 추가
  src/components/MatchDetail.vue
Labels: feat

#14 [REFACTOR] API 적용
  src/api/index.js
  src/components/MatchDetail.vue
Labels: refactor
